version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt
  test:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt
            pytest
  quality:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt
            flake8
  package:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt      
      - setup_remote_docker:
          version: 20.10.2
      - run: |
          TAG=$CIRCLE_SHA1
          docker build -t $DOCKER_USER/oclettings-docker-build:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push $DOCKER_USER/oclettings-docker-build:$TAG
          docker tag $DOCKER_USER/oclettings-docker-build:$TAG registry.heroku.com/oc-lettings-2/web
          HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
          docker push registry.heroku.com/oc-lettings-2/web
          heroku container:release web -a oc-lettings-2

workflows:
  build_and_test:
    jobs:
      - build
      - test
      - quality
      - package


