version: 2.1

commands:
  restore_cache_cmd:
    steps:
      - restore_cache:
          key: oclettings_venv-{{ .Branch }}-{{ checksum "requirements.txt" }}
  save_cache_cmd:
    steps:    
      - save_cache:
          key: oclettings_venv-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"

executors:
  default:
    docker:
      - image: circleci/python:3.9
        auth:
          username: $DOCKER_USER
          password: $DOCKER_ACCESS_TOKEN 

orbs:
  heroku: circleci/heroku@1.2.6

jobs:
  build:
    executor: default
    steps:
      - checkout
      - restore_cache_cmd
      - run:
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache_cmd
  test:  
    executor: default
    steps:
      - checkout
      - restore_cache_cmd
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            pytest
      - run:
          name: Building test report
          command: |
            . venv/bin/activate
            mkdir test-reports
            coverage run -m pytest
            coverage xml -o test-reports/coverage.xml
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports      

  linting:  
    executor: default
    steps:
      - checkout
      - restore_cache_cmd
      - run:
          name: Running linting
          command: |
            . venv/bin/activate
            flake8   
  package:
    executor: default
    steps:
      - checkout   
      - setup_remote_docker:
          version: 20.10.2
      - run:
          name: Building container
          command: |
            docker build -t $DOCKER_USER/oclettings-docker-build:$CIRCLE_SHA1 .   
      - run:
          name: Pushing container to Dockerhub
          command: |
            echo $DOCKER_ACCESS_TOKEN | docker login -u $DOCKER_USER --password-stdin
            docker push $DOCKER_USER/oclettings-docker-build:$CIRCLE_SHA1
  deploy:
    executor: default
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2      
      - run:
          name: Installing Heroku CLI
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh          
      - run:
          name: Pulling container from Dockerhub
          command: |
            echo $DOCKER_ACCESS_TOKEN | docker login -u $DOCKER_USER --password-stdin
            docker pull $DOCKER_USER/oclettings-docker-build:$CIRCLE_SHA1 
      - run:
          name: Pushing container to Heroku
          command: |
            heroku container:login
            docker tag $DOCKER_USER/oclettings-docker-build:$CIRCLE_SHA1 registry.heroku.com/$HEROKU_APP_NAME/web
            docker push registry.heroku.com/$HEROKU_APP_NAME/web
      - run:
          name: Releasing container
          command: |          
            heroku container:release web -a $HEROKU_APP_NAME

workflows:
  build_test_package_deploy:
    jobs:
      - build      
      - test:
          requires:
            - build
      - linting:
          requires:
            - build                           
      - package:
          requires:
            - test
            - linting
          filters:
            branches:
              only: main    
      - deploy:
          requires:
            - package




