version: 2.1

executors:
  default:
    docker:
      - image: circleci/python:3.9

orbs:
  heroku: circleci/heroku@1.2.6

jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt
      - save_cache:
          key: build-cache
          paths:
            - cache
  test:  
    executor: default
    steps:
      - restore_cache:
          keys: 
            - build-cache   
      - run:
          command: |
            pytest
  quality:
    executor: default
    steps:
      - restore_cache:
          keys: 
            - build-cache         
      - run:
          command: |
            flake8
  package:
    executor: default
    steps:
      - restore_cache:
          keys: 
            - build-cache        
      - setup_remote_docker:
          version: 20.10.2
      - run: |
          TAG=$CIRCLE_SHA1
          sudo curl https://cli-assets.heroku.com/install.sh | sh
          docker build -t $DOCKER_USER/oclettings-docker-build:$TAG .
          echo $DOCKER_ACCESS_TOKEN | docker login -u $DOCKER_USER --password-stdin
          docker push $DOCKER_USER/oclettings-docker-build:$TAG
          docker tag $DOCKER_USER/oclettings-docker-build:$TAG registry.heroku.com/oc-lettings-2/web
          docker tag $DOCKER_USER/oclettings-docker-build:$TAG $DOCKER_USER/oclettings-docker-build:latest
          heroku container:login
          docker push registry.heroku.com/oc-lettings-2/web
          heroku container:release web -a oc-lettings-2

workflows:
  build_and_test:
    jobs:
      - build
      - test
      - quality
      - package


