version: 2.1

commands:
  restore_cache_cmd:
    steps:
      - restore_cache:
          key: oclettings_env-{{ .Branch }}-{{ checksum "requirements.txt" }}
  save_cache_cmd:
    steps:    
      - save_cache:
          key: oclettings_env-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"

executors:
  default:
    docker:
      - image: circleci/python:3.9
        auth:
          username: $DOCKER_USER
          password: $DOCKER_ACCESS_TOKEN 

orbs:
  heroku: circleci/heroku@1.2.6

jobs:
  build:
    executor: default
    steps:
      - checkout
      - restore_cache_cmd
      - run:
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache_cmd
  test:  
    executor: default
    steps:
      - checkout
      - restore_cache_cmd
      - run:
          command: |
            . venv/bin/activate
            pytest
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test-results
      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: test-results
          destination: tr1            
  # quality:
  #   executor: default
  #   steps:
  #     - restore_cache:
  #         keys: 
  #           - build-cache         
  #     - run:
  #         command: |
  #           flake8
  package:
    executor: default
    steps:
      - restore_cache:
          keys: 
            - build-cache        
      - setup_remote_docker:
          version: 20.10.2
      - run: |
          TAG=$CIRCLE_SHA1
          sudo curl https://cli-assets.heroku.com/install.sh | sh
          docker build -t $DOCKER_USER/oclettings-docker-build:$TAG .
          echo $DOCKER_ACCESS_TOKEN | docker login -u $DOCKER_USER --password-stdin
          docker push $DOCKER_USER/oclettings-docker-build:$TAG
          docker tag $DOCKER_USER/oclettings-docker-build:$TAG registry.heroku.com/oc-lettings-2/web
          docker tag $DOCKER_USER/oclettings-docker-build:$TAG $DOCKER_USER/oclettings-docker-build:latest
          heroku container:login
          docker push registry.heroku.com/oc-lettings-2/web
          heroku container:release web -a oc-lettings-2

workflows:
  build_and_test:
    jobs:
      - build      
      - test:
          requires:
            - build            
      # - quality
      # - package


